export interface FragmentDefinition {
  id: string;
  label: string;
  x: number;
  y: number;
  depth: 'back' | 'mid' | 'front';
  kind: 'default' | 'mono' | 'note' | 'confluence' | 'pdf';
  angle: number;
  driftX: number;
  driftY: number;
  period: number;
  phase: number;
}

export const fragmentLayout: FragmentDefinition[] = [
  {
    id: 'frag-1',
    label: 'Edit 4023: Mod-25 + E&M same DOS',
    x: 270,
    y: 176,
    depth: 'front',
    kind: 'mono',
    angle: -7,
    driftX: 18,
    driftY: 14,
    period: 190,
    phase: 0.2,
  },
  {
    id: 'frag-2',
    label: 'COSMOS.CLM_DTL',
    x: 650,
    y: 112,
    depth: 'back',
    kind: 'mono',
    angle: 5,
    driftX: 12,
    driftY: 10,
    period: 210,
    phase: 0.8,
  },
  {
    id: 'frag-3',
    label: 'Exclusion list - Q2 refresh?',
    x: 1040,
    y: 152,
    depth: 'mid',
    kind: 'default',
    angle: -4,
    driftX: 16,
    driftY: 12,
    period: 220,
    phase: 1.3,
  },
  {
    id: 'frag-4',
    label: "Policy update: see Raj's email",
    x: 1310,
    y: 232,
    depth: 'front',
    kind: 'note',
    angle: 8,
    driftX: 20,
    driftY: 15,
    period: 240,
    phase: 0.5,
  },
  {
    id: 'frag-5',
    label: 'FWAE intake form',
    x: 1560,
    y: 150,
    depth: 'back',
    kind: 'pdf',
    angle: -6,
    driftX: 13,
    driftY: 11,
    period: 215,
    phase: 1.8,
  },
  {
    id: 'frag-6',
    label: 'Adjudication routing - Tier 3',
    x: 194,
    y: 430,
    depth: 'mid',
    kind: 'confluence',
    angle: 4,
    driftX: 15,
    driftY: 17,
    period: 236,
    phase: 0.9,
  },
  {
    id: 'frag-7',
    label: 'SELECT * FROM clm WHERE ...',
    x: 486,
    y: 378,
    depth: 'front',
    kind: 'mono',
    angle: -3,
    driftX: 18,
    driftY: 14,
    period: 260,
    phase: 1.7,
  },
  {
    id: 'frag-8',
    label: 'Slack: #pi-investigations',
    x: 824,
    y: 436,
    depth: 'mid',
    kind: 'default',
    angle: -1,
    driftX: 15,
    driftY: 13,
    period: 205,
    phase: 0.1,
  },
  {
    id: 'frag-9',
    label: 'Provider taxonomy mapping',
    x: 1136,
    y: 402,
    depth: 'back',
    kind: 'confluence',
    angle: 7,
    driftX: 12,
    driftY: 10,
    period: 280,
    phase: 1.4,
  },
  {
    id: 'frag-10',
    label: 'Galaxy -> NDB join key?',
    x: 1458,
    y: 456,
    depth: 'mid',
    kind: 'note',
    angle: -8,
    driftX: 18,
    driftY: 14,
    period: 225,
    phase: 2.1,
  },
  {
    id: 'frag-11',
    label: 'Vendor edits - last updated 2023?',
    x: 350,
    y: 720,
    depth: 'back',
    kind: 'pdf',
    angle: -5,
    driftX: 15,
    driftY: 12,
    period: 240,
    phase: 2.4,
  },
  {
    id: 'frag-12',
    label: 'ask Raj?',
    x: 760,
    y: 760,
    depth: 'front',
    kind: 'note',
    angle: 10,
    driftX: 21,
    driftY: 18,
    period: 195,
    phase: 0.6,
  },
  {
    id: 'frag-13',
    label: 'Policy PDF - reimbursement logic',
    x: 1120,
    y: 744,
    depth: 'mid',
    kind: 'pdf',
    angle: -2,
    driftX: 16,
    driftY: 13,
    period: 255,
    phase: 1.9,
  },
  {
    id: 'frag-14',
    label: 'Confluence: PI knowledge hub',
    x: 1472,
    y: 720,
    depth: 'front',
    kind: 'confluence',
    angle: 6,
    driftX: 19,
    driftY: 16,
    period: 235,
    phase: 1.1,
  },
];
